spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: sapw
management:
  endpoints:
    web:
      exposure:
        include: "*"
