insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("LED티비", "가전제품", 100, "LG", 10, "최신형 TV")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("런닝화", "잡화", 200, "Nike", 20, "최고의 내구성")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("침대", "가구", 300, "시몬스", 30, "푹신푹신")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("테이블", "가구", 400, "이케아", 40, "튼튼해요")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("김치냉장고", "가전제품", 500, "LG", 50, "최고의 성능")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("스우시", "잡화", 600, "나이키", 60, "이뻐요")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("시계", "잡화", 700, "이케아", 70, "오각형시계")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("냉장고", "가전제품", 800, "LG", 80, "발열이 적어요")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("맥북프로", "가구", 900, "애플", 90, "2020년 신상")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("의자", "가구", 1000, "이케아", 100, "완전이뻐요")
